### ISSUE TITLE
Native modules support

### ISSUE THREAD

**Issue by ndrantotiana** [fearthecowboy/static-link#1]
Does native modules require work?
I tried to use ZeroMQ in my project alongside with static-link and it seems that my module is not found.
I don't know if it is related to the fact that I'm building and running it on Windows, please see that it appends **"C:"** to the path. Anyone knows what should I do to fix it?

> module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: The specified module could not be found.
\\?\C:\node_modules\zeromq\build\Release\zmq.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (C:\Users\IEUser\14\dist\static-loader.js:835:16)
    at Module.load (module.js:565:32)

Thank you in advance.

**Comment by fearthecowboy** [comment]
I don't think native modules work at the moment, as my suspicion is that they rely on the native loader. That'd be a bit tricky to fix. I might be able to look at that after I get back from vacation at the end of summer
