### ISSUE TITLE
Cannot static link electron app "AthenaPDF"

### ISSUE THREAD

**Issue by sxiii** [fearthecowboy/static-link#2]
Hi!

I'm trying to pack & statically link the app called "[AthenaPDF](https://github.com/arachnys/athenapdf)".

I've changed the package.json accordingly:
<details>
  <summary>Click to expand</summary>
<code>
{
  "name": "athenapdf",
  "version": "2.16.0",
  "description": "A simple CLI tool to convert HTML to PDF from a local file or a URL to a web page using Electron (Chromium).",
  "keywords": [
    "electron",
    "chrome",
    "cli",
    "html",
    "pdf",
    "converter",
    "generate"
  ],
  "homepage": "https://www.athenapdf.com/",
  "bugs": {
    "url": "https://github.com/arachnys/athenapdf/issues"
  },
  "license": "MIT",
  "author": "Ian Lai <ian@arachnys.com>",
  "bin": "./bin/athenapdf",
  "main": "athenapdf.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/arachnys/athenapdf.git"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "clean": "rm -rf build/",
    "build:prepare": "mkdir -p build/ && cp -r src/ build/artifacts/ && cp package.json build/artifacts/ && cd build/artifacts/ && npm i --production",
    "build:linux": "electron-packager build/artifacts/ athenapdf --platform=linux --arch=x64 --electron-version=3.1.13 --out=build/ --overwrite --asar --no-prune",
    "build": "npm run clean && npm run build:prepare && npm run build:linux",
    "static-link": "static-link"
  },
  "dependencies": {
    "electron": "^3.1.13",
    "commander": "^2.9.0",
    "rw": "^1.3.2"
  },
  "devDependencies": {
    "electron-packager": "^12.1.0",
    "static-link": "*"
  },
  "static-link": {
    "dependencies": {
      "chalk": "*",
      "marked": "*",
      "marked-terminal": "*",
      "yarn": "^1.1.0",
      "commander": "^2.9.0",
      "electron": "3.1.13",
      "rw": "^1.3.2"
    }
  }
}
</code>
</details>

Now, I am doing the following commands:
```
npm i
npm run build
npm run static-link
./bin/athenapdf
```
And, finally, I got this error (even after I found magic flag --no-prune for the electron-packager it still does not work):
```
[sw@t490s cli]$ ./bin/athenapdf 
/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (/home/sw/work/athenapdf/cli/dist/static-loader.js:1:18512)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/sw/work/athenapdf/cli/bin/athenapdf:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
```

Do you have any clues on how to make this work @fearthecowboy ?
Thanks!
Den

**Comment by fearthecowboy** [comment]
You want to static-link an electron app!? 

oh, my ... uh, I'll have to see if that's even physically possible.

**Comment by sxiii** [comment]
Oh so you think it would be a really hard thing to do?

Actually, I realized that I don't need electron; rather than that just a chromium/chrome because they now support headless mode (and electron still need tricks like xvfb which I don't have).

But now it would be another quest to statistically link chromium... :dagger: :dancer:
